vich_uploader:
  db_driver: orm

  mappings:
    images:
      uri_prefix: /upload/images/property
      upload_destination: "%kernel.project_dir%/public/upload/images/property"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
